update to the latest archiso releng
t2linux/archiso-t2 pull request #4
Opened 2022-02-05 04:50 UTC by brad

I updated from the latest archiso releng from git and the iso boots for me now. Fixes #3

2022-02-05 06:43 UTC, NoaHimesaka1873 requested changes
Read the comments please

2022-02-05 06:43 UTC, NoaHimesaka1873 commented on archiso/airootfs/root/.automated_script.sh
> -    echo "After running pacstrap and before you go into chroot, please, *please* copy /t2kern to /mnt/t2kern just in case."
Add these lines again (and t2kern.txt), without these you can't access the local repo

2022-02-05 06:43 UTC, NoaHimesaka1873 commented on archiso/packages.x86_64
> +amd-ucode
You don't need this cuz there are no Macs with AMD CPU

2022-02-05 06:43 UTC, NoaHimesaka1873 commented on archiso/profiledef.sh
> +bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito' 'uefi-x64.systemd-boot.esp' 'uefi-x64.systemd-boot.eltorito')
We don't need MBR boot because we're targeting Macs, not old PCs

2022-02-05 06:43 UTC, NoaHimesaka1873 commented on archiso/packages.x86_64
> +virtualbox-guest-utils-nox
We don't need this because it's not designed to use with VM, we're targeting T2 Macs

2022-02-05 06:43 UTC, NoaHimesaka1873 commented on archiso/packages.x86_64
> -opendoas
You can delete or leave this, it's about user choice

2022-02-05 06:47 UTC, NoaHimesaka1873 requested changes

2022-02-05 06:47 UTC, NoaHimesaka1873 commented on archiso/airootfs/root/.automated_script.sh
> -    cat /root/t2kern.txt >> /etc/pacman.conf
Also this line

2022-02-05 15:25 UTC, brad commented
Updated, will test when Github finishes [building it](https://github.com/brad/archiso-t2/actions/runs/1799756817)

2022-02-05 15:49 UTC, brad commented
That is failing for me with the same issue from #3 Seems something in ed08cb6ce010cb9140ec1042bc6daa43401fe3c0 broke it

2022-02-05 16:09 UTC, NoaHimesaka1873 commented
I added MBR again, test if that works

2022-02-05 16:17 UTC, brad commented
> I added MBR again, test if that works

Sure, I'll try that. But first I'm testing removing `cat /root/t2kern.txt >> /etc/pacman.conf`

2022-02-05 16:23 UTC, NoaHimesaka1873 commented
> > I added MBR again, test if that works
> 
> Sure, I'll try that. But first I'm testing removing `cat /root/t2kern.txt >> /etc/pacman.conf`. I'm wondering why that is needed when `archiso/pacman.conf` already has the `[t2kern]` source

Because `archiso/pacman.conf` does not get moved to iso when building. We must add that source when booting.

2022-02-05 16:35 UTC, brad commented
> I added MBR again, test if that works

This is [building] now

2022-02-05 17:37 UTC, brad commented
Neither of those changes worked for me, I'm starting to wonder if I'm doing something wrong. I'm gonna rebuild the one that worked for me to see if that's still working. On discord if you want to chat more there

2022-02-06 02:17 UTC, brad commented
Is it possible that we actually need the `amd-ucode` package? It's right there in my screenshot in #3: "Failed to open file: arch\boot\amd-ucode.img"
Gonna try that

2022-02-06 03:24 UTC, brad commented
@NoaHimesaka1873 This is working now for me. Test iso is attached to [this workflow run](https://github.com/brad/archiso-t2/actions/runs/1801132087) if you want to try it

2022-02-06 03:25 UTC, NoaHimesaka1873 commented
> Is it possible that we actually need the `amd-ucode` package? It's right there in my photo in #3: "Failed to open file: arch\boot\amd-ucode.img"
> 
> Gonna try that
> 
> 
> 
> EDIT: That fixed it, I'll clean this up and let you know when it's tested working

Ah yes, forgot to mention if we are gonna remove that package we need to modify bootloader options but anyway, it's not too big so...

Merging.

2022-02-06 03:26 UTC, merged